<?php

/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile
?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
// $_productCollection = $block->getLoadedProductCollection();
$_productCollection = $block->getProductMediaCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
?>
<?php if (!$_productCollection): ?>
    <div class="message info empty">
        <div>
            <?php /* @escapeNotVerified */ echo __('Subscribe now to see the catalogs.'); ?>
        </div>
    </div>
<?php elseif (!$_productCollection->count()): ?>
    <div class="message info empty">
        <div>
            <?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?>
        </div>
    </div>
<?php else: ?>
    <div class="subTitle">
        Para ver alguno de los catálogos virtuales disponibles, da click en el botón de Ver Catálogo y se abrirá una ventana en donde podrás pasar página por página del catálogo.
        También puedes compartir el catálogo con tus clientes, simplemente da click en el botón Compartir, escribe el o los correos electrónicos a donde desees enviarlo, y un mensaje.
    </div>
    <?php
    $viewMode = 'grid';
    $image = 'category_page_grid';
    $showDescription = false;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?>">
        <?php $iterator = 1; ?>
        <ol class="products list items cataFlip product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
                <?php $url = $block->getPdfUrl($_product); ?>
                <?php if ($url || $block->getVideoUrl($_product)): ?>
                    <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                    <div class="product-item-info" data-container="product-grid">
                        <?php
                        $productImage = $block->getImage($_product, $image);
                        if ($pos != null) {
                            $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                    . 'top:' . $productImage->getHeight() . 'px;"';
                        }
                        ?>
                        <strong class="product name product-item-name">
                            <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                        </strong>
                        <?php if ($url): ?>
                            <a href="javascript:;" class="product photo product-item-photo showFlipbookAction" data-url="<?php /* @escapeNotVerified */ echo $url; ?>" tabindex="-1">
                                <?php echo $productImage->toHtml(); ?>
                            </a>
                        <?php else : ?>
                            <a class="multimedia" data-youtube="<?php echo $this->getVideoUrl($_product); ?>" tabindex="-1">
                                <?php echo $productImage->toHtml(); ?>
                            </a>    
                        <?php endif; ?>

                        <?php // Product Image ?>

                        <div class="product details product-item-details">
                            <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                            ?>

                            <?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
                            <?php echo $block->getProductDetailsHtml($_product); ?>

                            <div class="product-item-inner">
                                <?php if ($showDescription): ?>
                                    <div class="product description product-item-description">
                                        <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                        <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" title="<?php /* @escapeNotVerified */ echo $_productNameStripped ?>"
                                           class="action more"><?php /* @escapeNotVerified */ echo __('Learn More') ?></a>
                                    </div>
                                <?php endif; ?>
                            </div>
                            <?php if ($url): ?>
                                <div class="showFlipbook showFlipbookAction" id="showFlipbook" data-url="<?php /* @escapeNotVerified */ echo $url; ?>" >
                                    <img src="<?php echo $this->getViewFileUrl('Qbo_FlipBook::images/seeCatalog.png'); ?>" />
                                    <span><?php echo __('See Catalog'); ?></span>
                                </div>
                                <div  class="pdf share-form" id="share-form" data-prod ="<?php /* @escapeNotVerified */ echo $url; ?>" data-id="<?php echo $_product->getId() ?>" >
                                    <span><?php /* @escapeNotVerified */ echo __('Share'); ?></span>
                                    <img src="<?php echo $this->getViewFileUrl('Qbo_FlipBook::images/shareCatalog.png'); ?>" />
                                </div>
                            <?php else : ?>
                                <button  class="action  primary multimedia" data-youtube="<?php echo $this->getVideoUrl($_product); ?>">
                                    <span><?php /* @escapeNotVerified */ echo __('See'); ?></span>
                                </button>   
                            <?php endif; ?>
                        </div>
                    </div>
                    <?php echo($iterator == count($_productCollection) + 1) ? '</li>' : '' ?>
                <?php endif; ?>
            <?php endforeach; ?>
        </ol>
    </div>
    <div id="popup-multimedia" style="display:none">
        <div class="video-container">
            <iframe  width="100%" height="350px"  class="param-video" src=""></iframe>
        </div>
    </div>
    <div id="popup-share" style="display:none" data-prod="">
        <?php echo $block->getChildHtml('share_form') ?>
    </div>

    <div id="popupCustomFlipbook" style="display: none;"></div>

    <div data-mage-init='{"multimedia":{}}'></div>
    <?php echo $block->getToolbarHtml() ?>
    <?php if ($block->getMode() == 'grid'): ?>
        <script type="text/javascript">
            require([
                'jquery'
            ], function ($) {
                $('.main .products.grid .product-items li.product-item:nth-child(2n)').addClass('nth-child-2n');
                $('.main .products.grid .product-items li.product-item:nth-child(2n+1)').addClass('nth-child-2np1');
                $('.main .products.grid .product-items li.product-item:nth-child(3n)').addClass('nth-child-3n');
                $('.main .products.grid .product-items li.product-item:nth-child(3n+1)').addClass('nth-child-3np1');
                $('.main .products.grid .product-items li.product-item:nth-child(4n)').addClass('nth-child-4n');
                $('.main .products.grid .product-items li.product-item:nth-child(4n+1)').addClass('nth-child-4np1');
                $('.main .products.grid .product-items li.product-item:nth-child(5n)').addClass('nth-child-5n');
                $('.main .products.grid .product-items li.product-item:nth-child(5n+1)').addClass('nth-child-5np1');
                $('.main .products.grid .product-items li.product-item:nth-child(6n)').addClass('nth-child-6n');
                $('.main .products.grid .product-items li.product-item:nth-child(6n+1)').addClass('nth-child-6np1');
                $('.main .products.grid .product-items li.product-item:nth-child(7n)').addClass('nth-child-7n');
                $('.main .products.grid .product-items li.product-item:nth-child(7n+1)').addClass('nth-child-7np1');
                $('.main .products.grid .product-items li.product-item:nth-child(8n)').addClass('nth-child-8n');
                $('.main .products.grid .product-items li.product-item:nth-child(8n+1)').addClass('nth-child-8np1');
            });
        </script>
    <?php endif; ?>
<?php endif; ?>
