<?php

/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile
?>
<?php
/**
 * Product list template
 *
 * @var $block \Qbo\Capacitations\Block\Product\ListMedia
 */
?>
<?php
$_productCollection = $block->getProductMediaCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_imagehelper = $this->helper('Magento\Catalog\Helper\Image');

$_category_config = $this->helper('Smartwave\Porto\Helper\Data')->getConfig('porto_settings/category');
$_category_grid_config = $this->helper('Smartwave\Porto\Helper\Data')->getConfig('porto_settings/category_grid');
$_product_label_config = $this->helper('Smartwave\Porto\Helper\Data')->getConfig('porto_settings/product_label');
$move_actions = "";
$flex_grid = "";
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?php echo __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?php echo $block->getToolbarHtml() ?>
    <?php echo $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $hover_image = 'category_page_grid-hover';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
        $columns = 'columns' . $_category_grid_config['columns'];
        $move_actions = $_category_grid_config['move_actions'];
        if (isset($_category_grid_config['flex_grid']) && $_category_grid_config['flex_grid'])
            $flex_grid = "flex-grid";
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $hover_image = 'category_page_list-hover';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
        $columns = '';
    }
    $image_width = ($_category_config['ratio_width']) ? $_category_config['ratio_width'] : 300;
    $image_height = ($_category_config['ratio_height']) ? $_category_config['ratio_height'] : 300;
    ?>
    <div class="products wrapper <?php echo $viewMode; ?> <?php echo $columns; ?> <?php echo $flex_grid; ?> products-<?php echo $viewMode; ?>">
        <?php $iterator = 1; ?>
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
                <?php if ($_product->getPdfUrl() || $block->getVideoUrl($_product)): ?>
                    <?php echo($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                    <div class="product-item-info" data-container="product-grid">
                        <?php // Product Image ?>
                        <div class="product photo product-item-photo">
                            <?php if ($_product->getPdfUrl()): ?>
                                <a onclick=" window.open('<?php /* @escapeNotVerified */ echo $this->getUrl('flipbook/product/pdf', array('productId' => $_product->getId())) ?>', '_blank')" tabindex="-1">
                                <?php else : ?>
                                    <a class="multimedia" data-youtube="<?php echo $this->getVideoUrl($_product); ?>" tabindex="-1">    
                                    <?php endif; ?>

                                    <?php
                                    if ($_category_config['aspect_ratio'])
                                        $productImage = $_imagehelper->init($_product, $image)->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize($image_width);
                                    else
                                        $productImage = $_imagehelper->init($_product, $image)->resize($image_width, $image_height);
                                    $productImageUrl = $productImage->getUrl();
                                    ?>
                                    <img class="product-image-photo default_image" src="<?php echo $productImageUrl; ?>" alt="<?php echo $productImage->getLabel(); ?>"/>
                                    <?php if ($_category_config['alternative_image']): ?>
                                        <?php
                                        if ($_category_config['aspect_ratio'])
                                            $productHoverImage = $_imagehelper->init($_product, $hover_image)->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize($image_width);
                                        else
                                            $productHoverImage = $_imagehelper->init($_product, $hover_image)->resize($image_width, $image_height);
                                        $productHoverImageUrl = $productHoverImage->getUrl();
                                        ?>
                                        <?php if ($productImageUrl != str_replace("/thumbnail/", "/small_image/", $productHoverImageUrl)): ?>
                                            <img class="product-image-photo hover_image" src="<?php echo $productHoverImageUrl; ?>" alt="<?php echo $productHoverImage->getLabel(); ?>"/>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </a>
                                <?php
                                $product_label = "";
                                if ($_product_label_config['sale_label']) {
                                    $orgprice = $_product->getFinalPrice();
                                    $specialprice = $_product->getSpecialPrice();
                                    $specialfromdate = $_product->getSpecialFromDate();
                                    $specialtodate = $_product->getSpecialToDate();
                                    $today = time();
                                    if (!$specialprice)
                                        $specialprice = $orgprice;
                                    if ($specialprice < $orgprice) {
                                        if ((is_null($specialfromdate) && is_null($specialtodate)) || ($today >= strtotime($specialfromdate) && is_null($specialtodate)) || ($today <= strtotime($specialtodate) && is_null($specialfromdate)) || ($today >= strtotime($specialfromdate) && $today <= strtotime($specialtodate))) {
                                            if ($_product_label_config['sale_label_percent']) {
                                                $save_percent = 100 - round(($specialprice / $orgprice) * 100);
                                                $product_label .= '<div class="product-label sale-label">' . '-' . $save_percent . '%' . '</div>';
                                            } else {
                                                $product_label .= '<div class="product-label sale-label">' . $_product_label_config['sale_label_text'] . '</div>';
                                            }
                                        }
                                    }
                                }
                                if ($_product_label_config['new_label']) {
                                    $now = date("Y-m-d");
                                    $newsFrom = substr($_product->getData('news_from_date'), 0, 10);
                                    $newsTo = substr($_product->getData('news_to_date'), 0, 10);

                                    if ($newsTo != '' || $newsFrom != '') {
                                        if (($newsTo != '' && $newsFrom != '' && $now >= $newsFrom && $now <= $newsTo) || ($newsTo == '' && $now >= $newsFrom) || ($newsFrom == '' && $now <= $newsTo)) {
                                            $product_label .= '<div class="product-label new-label">' . $_product_label_config['new_label_text'] . '</div>';
                                        }
                                    }
                                }
                                if ($product_label)
                                    echo '<div class="product-labels">' . $product_label . '</div>';
                                ?>
                                <?php if ($_category_config['actions'] && $move_actions): ?>

                                <?php endif; ?>
                        </div>
                        <div class="product details product-item-details">
                            <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                            ?>
                            <a class="product-item-link"><?php echo $_product->getName() ?></a>
                        </div>
                        <?php if ($_product->getPdfUrl()): ?>
                            <button  class="action  primary pdf" onclick=" window.open('<?php /* @escapeNotVerified */ echo $this->getUrl('flipbook/product/pdf', array('productId' => $_product->getId())) ?>', '_blank')" >
                                <span><?php /* @escapeNotVerified */ echo __('See'); ?></span>
                            </button>
                            <button  class="action  primary pdf" id="share-form" data-prod ="<?php /* @escapeNotVerified */ echo $this->getUrl('flipbook/product/pdf', array('productId' => $_product->getId())) ?>" data-id="<?php echo $_product->getId()?>" >
                                <span><?php /* @escapeNotVerified */ echo __('Share'); ?></span>
                            </button>
                        <?php else: ?>
                            <button  class="action  primary multimedia" data-youtube="<?php echo $this->getVideoUrl($_product); ?>">
                                <span><?php /* @escapeNotVerified */ echo __('See'); ?></span>
                            </button>
                        <?php endif; ?>
                    </div>
                    <?php echo($iterator == count($_productCollection) + 1) ? '</li>' : '' ?>
                <?php endif; ?>
            <?php endforeach; ?>
        </ol>
    </div>
    <div id="popup-multimedia" style="display:none">
        <div class="video-container">
            <iframe  width="100%" height="350px"  class="param-video" src=""></iframe>
        </div>
    </div>
    <div id="popup-share" style="display:none" data-prod="">
        <?php echo $block->getChildHtml('share_form') ?>
    </div>
    <div data-mage-init='{"multimedia":{}}'></div>
    <?php echo $block->getToolbarHtml() ?>
    <?php if ($block->getMode() == 'grid'): ?>
        <script type="text/javascript">
            require([
                'jquery'
            ], function ($) {
                $('.main .products.grid .product-items li.product-item:nth-child(2n)').addClass('nth-child-2n');
                $('.main .products.grid .product-items li.product-item:nth-child(2n+1)').addClass('nth-child-2np1');
                $('.main .products.grid .product-items li.product-item:nth-child(3n)').addClass('nth-child-3n');
                $('.main .products.grid .product-items li.product-item:nth-child(3n+1)').addClass('nth-child-3np1');
                $('.main .products.grid .product-items li.product-item:nth-child(4n)').addClass('nth-child-4n');
                $('.main .products.grid .product-items li.product-item:nth-child(4n+1)').addClass('nth-child-4np1');
                $('.main .products.grid .product-items li.product-item:nth-child(5n)').addClass('nth-child-5n');
                $('.main .products.grid .product-items li.product-item:nth-child(5n+1)').addClass('nth-child-5np1');
                $('.main .products.grid .product-items li.product-item:nth-child(6n)').addClass('nth-child-6n');
                $('.main .products.grid .product-items li.product-item:nth-child(6n+1)').addClass('nth-child-6np1');
                $('.main .products.grid .product-items li.product-item:nth-child(7n)').addClass('nth-child-7n');
                $('.main .products.grid .product-items li.product-item:nth-child(7n+1)').addClass('nth-child-7np1');
                $('.main .products.grid .product-items li.product-item:nth-child(8n)').addClass('nth-child-8n');
                $('.main .products.grid .product-items li.product-item:nth-child(8n+1)').addClass('nth-child-8np1');
            });
        </script>
    <?php endif; ?>
<?php endif; ?>